version: 0.2.0.{build}
install:
- cinst -y pester
- git clone https://github.com/PowerShell/DscResource.Tests
build: off
on_finish:
- ps: >-
    $stagingDirectory = (Resolve-Path ..).Path

    $pwd = Join-Path $pwd "modules\xSharePoint"

    Remove-Item (Join-Path $pwd "xSharePoint.pssproj")

    $zipFile = Join-Path $stagingDirectory "$(Split-Path $pwd -Leaf).zip"

    Add-Type -assemblyname System.IO.Compression.FileSystem

    [System.IO.Compression.ZipFile]::CreateFromDirectory($pwd, $zipFile)

    @(
        (ls $zipFile)
    ) | % { Push-AppveyorArtifact $_.FullName }